### ISSUE TITLE
ImageJ-Canvas

### ISSUE THREAD

**Issue by mutterer** [Bio7/EclipseImageJ1Plugin#2]
It would be nice if the ImageJ-Canvas view had listeners from the beginning, even when empty. Currently, there needs to be an image in it, and you need to click the image to get the listeners and be able to use IJ shortcuts.

**Comment by Bio7** [comment]
The ImageJ canvas interface is integrated into a SWT CTab panel. When you open an image the Imagej panel is nested into an CTabItem. Some listeners are already installed on the CTab interface, e.g., you can drag and drop images on the CTab interface. 

It would be possible to install some further key commands on the CTab interface. Which commands would you like to have integrated?

**Comment by Bio7** [comment]
I added a key listener to the CTabFolder which adds several commands to this component (The same commands which you get with "List Shortcuts". 
See:
https://github.com/Bio7/EclipseImageJ1Plugin/commit/719af10b067afa2cd101fd4c0dbb0cccb32b981a

**Comment by mutterer** [comment]
Nice, this should provide for all necessary shortcuts. Thank you !
