### ISSUE TITLE
Update Site Inactive

### ISSUE THREAD

**Issue by DbBRICK** [Bio7/EclipseImageJ1Plugin#3]
Update site "https://bio7.github.io/imagej/" returns error 404, will not work with ImageJ.

**Comment by Bio7** [comment]
Have you added 

https://bio7.github.io/imagej

as an update site to Eclipse?

Please note that this is a directory for an Eclipse plugin and not a regular *html link.

The github source repo (where the link simply redirects to) is here:

https://github.com/Bio7/bio7.github.io/tree/master/imagej
